spring.datasource.url=jdbc:postgresql://localhost:5437/alloca_db
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=ALLOCA
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jackson.serialization.write-dates-as-timestamps=false

# Swagger
# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html